import {describe,it,expect} from 'vitest';
import {createGame,applyCommand,nextAutoCommand} from './engine';
import {CARDS_BY_ID,DIGITAL_CARDS} from '../data/cards';
import {ITEMS} from '../data/config';
import {validateGameState} from '../persistence/validate';
import type {GameState,Command} from './types';
const setup=()=>createGame(['Iago','Milena','AR2'].map((name,i)=>({id:`p${i}`,name,color:'#abc',symbol:'X',portrait:'/x.png'})),{}, {seed:91,shuffleOrder:false});
function run(s:GameState,c:Command){const r=applyCommand(s,{commandId:`t-${s.revision}`,expectedRevision:s.revision,command:c});expect(r.rejected).toBeUndefined();expect(validateGameState(r.state)).toEqual({ok:true,errors:[]});return r.state;}
function preview(s:GameState,id:string){s.phase='awaitingInteraction';s.pending={kind:'cardPreview',playerId:s.order[s.activeIndex],cardId:id,category:CARDS_BY_ID[id].category};return s;}
const card=(s:GameState,id:string)=>run(preview(s,id),{type:'confirmCard'});
describe('cartas da Milena',()=>{
 it('13 eventos, 6 poderes a 5 moedas, raras cinco vezes menos frequentes que comuns',()=>{const s=setup();expect(DIGITAL_CARDS).toHaveLength(13);expect(s.config.shopItems).toHaveLength(6);expect(s.config.shopItems.map(id=>ITEMS[id].price)).toEqual([5,5,5,5,5,5]);expect(DIGITAL_CARDS.filter(c=>c.weight===1)).toHaveLength(4);});
 it('carta digital tem avanço automático; física continua por código',()=>{const s=preview(setup(),'MA01');expect(nextAutoCommand(s)).toEqual({type:'confirmCard'});s.config.cardMode='physical';expect(nextAutoCommand(s)).toBeNull();});
 it('rouba banana e metade das moedas, arredondando para baixo, sem criar saldo',()=>{let s=setup();s.players.p1.golden=2;s=card(s,'MS01');s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.players.p0.golden).toBe(1);expect(s.players.p1.golden).toBe(1);s.players.p1.common=11;s=card(s,'MS04');s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.players.p0.common).toBe(15);expect(s.players.p1.common).toBe(6);});
 it('Pickpocket exige descarte de uma carta antiga quando a mão está cheia',()=>{let s=setup();s.players.p0.inventory=['a','b','c'].map(uid=>({uid,itemId:'dadoDuplo'}));s.players.p1.inventory=[{uid:'stolen',itemId:'dadoCerteiro'}];s=card(s,'MS03');s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.pending?.kind).toBe('discardPower');expect(s.players.p0.inventory).toHaveLength(3);expect(s.players.p1.inventory).toHaveLength(0);s=run(s,{type:'discardPower',uid:'a'});expect(s.players.p0.inventory.map(i=>i.uid)).toEqual(['b','c','stolen']);expect(applyCommand(s,{commandId:'dup',expectedRevision:s.revision,command:{type:'discardPower',uid:'b'}}).rejected).toBeDefined();});
 it('Blindado automático anula perda e ataque, não recompensa nem Iagugu',()=>{let s=setup();s.players.p0.golden=2;s.players.p0.inventory=[{uid:'shield',itemId:'blindado'}];s=card(s,'MA07');expect(s.players.p0.golden).toBe(2);expect(s.players.p0.inventory).toHaveLength(0);s.players.p1.inventory=[{uid:'shield2',itemId:'blindado'}];s.players.p1.golden=1;s=card(s,'MS01');s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.players.p1.golden).toBe(1);expect(s.players.p1.inventory).toHaveLength(0);s.players.p0.inventory=[{uid:'shield3',itemId:'blindado'}];s=card(s,'MS02');expect(s.players.p0.inventory).toHaveLength(1);});
 it('Blindado não aparece como Reverse nem bloqueia um poder antigo',()=>{let s=setup();s.phase='awaitingItemChoice';s.pending={kind:'itemChoice',playerId:'p0'};s.players.p0.inventory=[{uid:'attack',itemId:'casca'}];s.players.p1.inventory=[{uid:'shield',itemId:'blindado'}];s=run(s,{type:'useItem',uid:'attack'});s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.pending).toBeNull();expect(s.players.p1.common).toBe(7);expect(s.players.p1.inventory[0].itemId).toBe('blindado');});
 it('Tudo ou Nada transfere todo saldo do perdedor, independente do saldo do vencedor',()=>{let s=setup();s.players.p0.common=3;s.players.p1.common=40;s=card(s,'MS06');s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.pending).toMatchObject({kind:'duelResult',allIn:true});s=run(s,{type:'resolveDuel',winnerId:'p0'});expect(s.players.p0.common).toBe(43);expect(s.players.p1.common).toBe(0);});
 it('teletransporta à árvore, oferece compra e retoma sem ativar casa ou prêmio de volta',()=>{let s=setup();s.players.p0.common=50;s=card(s,'MS05');expect(s.pending?.kind).toBe('pedestal');s=run(s,{type:'buyGolden'});expect(s.players.p0.golden).toBe(1);expect(nextAutoCommand(s)).toEqual({type:'continueHarvest'});s=run(s,{type:'continueHarvest'});s=run(s,{type:'step'});expect(s.phase).toBe('turnEnd');expect(s.players.p0.common).toBe(30);});
 it('sem saldo ou sem vítimas, encerra evento sem decisão vazia',()=>{let s=card(setup(),'MS05');expect(s.pending).toBeNull();for(const id of ['MS01','MS03']){s=card(setup(),id);expect(s.pending).toBeNull();expect(s.phase).toBe('turnEnd');}});
 it('azar social registra duração e exceção AR2, sem confirmação',()=>{let s=setup();s.activeIndex=2;s=card(s,'MA02');expect(s.players.p2.tasks).toEqual([{cardId:'MA02',untilRound:3}]);expect(s.phase).toBe('turnEnd');s=card(s,'MA04');expect(s.players.p2.tasks?.at(-1)?.untilRound).toBe(3);});
 it('Preguição consome um poder, limita apenas a próxima rolagem mesmo com dado duplo',()=>{let s=setup();s.phase='awaitingItemChoice';s.pending={kind:'itemChoice',playerId:'p0'};s.players.p0.inventory=[{uid:'slow',itemId:'preguicao'}];s=run(s,{type:'useItem',uid:'slow'});s=run(s,{type:'chooseTarget',targetId:'p1'});expect(s.players.p1.slowNextRoll).toBe(true);expect(s.players.p0.inventory).toHaveLength(0);s.activeIndex=1;s.phase='readyToRoll';s.diceMultiplier=2;s.chosenDice=10;s=run(s,{type:'rollDice'});expect(s.dice).toBeGreaterThanOrEqual(1);expect(s.dice).toBeLessThanOrEqual(3);expect(s.players.p1.slowNextRoll).toBeUndefined();});
});
