import {describe,it,expect} from 'vitest';
import {createGame,applyCommand} from './engine';
import {createV4Map as createDefaultMap,createV3Map} from '../data/map';
import {validateGameState} from '../persistence/validate';
import type {GameState,Command} from './types';
const seeds=['Iago','Milena'].map((name,i)=>({id:`p${i}`,name,color:'#abc',symbol:'X',portrait:'/x.png'}));
function game(){return createGame(seeds,{}, {seed:87,shuffleOrder:false,map:createDefaultMap()});}
function run(s:GameState,command:Command){const r=applyCommand(s,{commandId:'t',expectedRevision:s.revision,command});expect(r.rejected).toBeUndefined();expect(validateGameState(r.state)).toEqual({ok:true,errors:[]});return r.state;}
function walk(id:string,remaining=1){const s=game();s.players.p0.nodeId=id;s.phase='moving';s.movement={remaining,traversed:[],activatesSpaces:true,direction:'forward'};return s;}
describe('v4: regras de almoço',()=>{
 it('Iagugu rouba dez moedas sem taxa e preserva a soma dos saldos',()=>{let s=walk('a0');s.players.p1.common=25;s=run(s,{type:'step'});s=run(s,{type:'rob',currency:'common',targetId:'p1'});expect([s.players.p0.common,s.players.p1.common]).toEqual([20,15]);});
 it('tem a distribuição exata, sem neutras e com Iagugu em rota oposta à árvore',()=>{const m=createDefaultMap();const counts=Object.values(m.nodes).reduce((a,n)=>({...a,[n.kind]:(a[n.kind]??0)+1}),{} as Record<string,number>);expect(counts).toEqual({start:1,plus:10,minus:6,luck:8,unluck:8,duel:3});expect(m.stops?.find(s=>s.kind==='iagugu')?.from).toBe('a0');expect(m.stops?.find(s=>s.id==='tree-temple')?.from).toBe('m6');});
 it('paga +10 ao chegar no início uma vez, inclusive com movimento restante',()=>{for(const remaining of [1,2]){const s=run(walk('m27',remaining),{type:'step'});expect(s.players.p0.common).toBe(20);const next=run(s,remaining===1?{type:'resolveSpace'}:{type:'step'});expect(next.players.p0.common).toBe(20);}});
 it('não paga bônus no spawn, recuo, troca ou mapa antigo',()=>{expect(game().players.p0.common).toBe(10);const s=walk('m27');s.movement!.activatesSpaces=false;expect(run(s,{type:'step'}).players.p0.common).toBe(10);const old=walk('m27');old.map=createV3Map();expect(run(old,{type:'step'}).players.p0.common).toBe(10);});
 it('Iagugu não gasta passo, transfere no máximo o saldo e resolve uma vez',()=>{let s=walk('a0',2);s.players.p1.common=3;s=run(s,{type:'step'});expect(s.pending?.kind).toBe('iagugu');expect(s.movement?.remaining).toBe(2);s=run(s,{type:'rob',currency:'common',targetId:'p1'});expect(s.players.p0.common).toBe(13);expect(s.players.p1.common).toBe(0);expect(applyCommand(s,{commandId:'dup',expectedRevision:s.revision,command:{type:'rob',currency:'common',targetId:'p1'}}).rejected).toBeTruthy();s=run(s,{type:'step'});expect(s.players.p0.nodeId).toBe('a1');expect(s.movement?.remaining).toBe(1);});
 it('roubo de banana cobra 40 e transfere sem criar fruto',()=>{let s=walk('a0');s.players.p0.common=40;s.players.p1.golden=1;s=run(s,{type:'step'});const rejected=applyCommand(s,{commandId:'self',expectedRevision:s.revision,command:{type:'rob',currency:'golden',targetId:'p0'}});expect(rejected.rejected).toBeTruthy();s=run(s,{type:'rob',currency:'golden',targetId:'p1'});expect([s.players.p0.common,s.players.p0.golden,s.players.p1.golden]).toEqual([0,1,0]);});
 it('saldo insuficiente não cobra nem transfere banana',()=>{let s=walk('a0');s.players.p1.golden=1;s=run(s,{type:'step'});const r=applyCommand(s,{commandId:'x',expectedRevision:s.revision,command:{type:'rob',currency:'golden',targetId:'p1'}});expect(r.rejected).toBeTruthy();expect(r.state).toEqual(s);});
 it('duelo só ativa no destino e aposta não ultrapassa saldos',()=>{let s=walk('m5');s=run(s,{type:'step'});s=run(s,{type:'resolveSpace'});expect(s.pending?.kind).toBe('duelBet');expect(applyCommand(s,{commandId:'x',expectedRevision:s.revision,command:{type:'setDuelBet',amount:11}}).rejected).toBeTruthy();s=run(s,{type:'setDuelBet',amount:5});s=run(s,{type:'resolveDuel',winnerId:'p1'});expect([s.players.p0.common,s.players.p1.common,s.phase]).toEqual([5,15,'turnEnd']);expect(applyCommand(s,{commandId:'dup',expectedRevision:s.revision,command:{type:'resolveDuel',winnerId:'p1'}}).rejected).toBeTruthy();const passing=run(walk('m5',2),{type:'step'});expect(passing.pending).toBeNull();expect(passing.phase).toBe('moving');});
 it('duelo amistoso sem saldo e empate não criam moedas',()=>{let s=game();s.players.p0.nodeId='m6';s.players.p0.common=0;s.phase='resolvingSpace';s=run(s,{type:'resolveSpace'});s=run(s,{type:'setDuelBet',amount:0});s=run(s,{type:'resolveDuel',winnerId:null});expect(s.players.p0.common).toBe(0);expect(s.players.p1.common).toBe(10);expect(s.phase).toBe('turnEnd');});
 it('árvore ativa pausa no piso, salva e retoma sem gastar passo adicional',()=>{let s=walk('m6',2);s.players.p0.common=30;s=run(s,{type:'step'});expect(s.pending?.kind).toBe('pedestal');expect(s.movement?.remaining).toBe(2);s=run(s,{type:'buyGolden'});expect(s.pending?.kind).toBe('harvest');s=run(JSON.parse(JSON.stringify(s)),{type:'continueHarvest'});s=run(s,{type:'step'});expect(s.players.p0.nodeId).toBe('m7');expect(s.movement?.remaining).toBe(1);expect(s.players.p0.golden).toBe(1);});
});
